# Generated by Django 2.1.7 on 2019-05-23 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100)),
                ('Tipo', models.CharField(blank=True, max_length=100)),
                ('Cantidad', models.IntegerField(blank=True, null=True)),
                ('PrecioCompra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Descripcion', models.TextField(blank=True)),
                ('Foto', models.ImageField(height_field=200, upload_to='', width_field=200)),
                ('Existencia', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100)),
                ('Telefono', models.IntegerField(blank=True, null=True)),
                ('Direccion', models.TextField(blank=True)),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaCompra', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Cantidad', models.IntegerField(blank=True, null=True)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Producto')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Proveedor')),
            ],
        ),
    ]
