# Generated by Django 2.1.7 on 2019-05-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Existencia',
        ),
    ]
