# Generated by Django 2.1.7 on 2019-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_remove_producto_existencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Foto',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='', width_field=200),
        ),
    ]
