# Generated by Django 2.1.7 on 2019-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_auto_20190528_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
