# Generated by Django 2.1.7 on 2019-06-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_auto_20190601_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
