# Generated by Django 2.1.7 on 2019-05-25 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='Cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='Empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Empleado'),
            preserve_default=False,
        ),
    ]
