# Generated by Django 2.1.7 on 2019-05-27 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_auto_20190527_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='Usuarios.Usuario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to='Usuarios.Usuario'),
        ),
    ]
